language: python
python:
  - 2.7
  - 3.6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libatlas-base-dev
      - gfortran
      - gcc-4.9
      - g++-4.9
env:
    - CC=gcc-4.9 CXX=g++-4.9
before_install:
 - pip install --upgrade pip setuptools wheel
 - pip install --only-binary=all scipy cython coveralls
 - pip install denovonear
install:
 - python setup.py install
script:
 - python -m coverage run --source=./severity -m unittest discover
after_success:
 - coveralls
